import type { Category } from "@/types/expense";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "groceries",
    name: "Продукти",
    emoji: "🛒",
    color: "#22c55e",
    isCustom: false,
  },
  {
    id: "housing",
    name: "Житло",
    emoji: "🏠",
    color: "#8b5cf6",
    isCustom: false,
  },
  {
    id: "transport",
    name: "Транспорт",
    emoji: "🚗",
    color: "#3b82f6",
    isCustom: false,
  },
  {
    id: "restaurants",
    name: "Ресторани",
    emoji: "🍽️",
    color: "#f97316",
    isCustom: false,
  },
  {
    id: "entertainment",
    name: "Розваги",
    emoji: "🎬",
    color: "#ec4899",
    isCustom: false,
  },
  {
    id: "health",
    name: "Здоров'я",
    emoji: "💊",
    color: "#14b8a6",
    isCustom: false,
  },
  {
    id: "beauty",
    name: "Краса",
    emoji: "💅",
    color: "#f472b6",
    isCustom: false,
  },
  {
    id: "clothes",
    name: "Одяг",
    emoji: "👗",
    color: "#a78bfa",
    isCustom: false,
  },
  {
    id: "education",
    name: "Освіта",
    emoji: "📚",
    color: "#06b6d4",
    isCustom: false,
  },
  {
    id: "gifts",
    name: "Подарунки",
    emoji: "🎁",
    color: "#f43f5e",
    isCustom: false,
  },
  {
    id: "travel",
    name: "Подорожі",
    emoji: "✈️",
    color: "#0ea5e9",
    isCustom: false,
  },
  {
    id: "subscriptions",
    name: "Підписки",
    emoji: "📱",
    color: "#6366f1",
    isCustom: false,
  },
  {
    id: "pets",
    name: "Улюбленці",
    emoji: "🐾",
    color: "#84cc16",
    isCustom: false,
  },
  {
    id: "home",
    name: "Дім і побут",
    emoji: "🧹",
    color: "#eab308",
    isCustom: false,
  },
  {
    id: "tech",
    name: "Техніка",
    emoji: "💻",
    color: "#64748b",
    isCustom: false,
  },
  {
    id: "sports",
    name: "Спорт",
    emoji: "🏋️",
    color: "#10b981",
    isCustom: false,
  },
  { id: "taxi", name: "Таксі", emoji: "🚕", color: "#fbbf24", isCustom: false },
  {
    id: "coffee",
    name: "Кава",
    emoji: "☕",
    color: "#92400e",
    isCustom: false,
  },
  {
    id: "utilities",
    name: "Комунальні",
    emoji: "💡",
    color: "#f59e0b",
    isCustom: false,
  },
  {
    id: "internet",
    name: "Інтернет",
    emoji: "🌐",
    color: "#2563eb",
    isCustom: false,
  },
  {
    id: "phone",
    name: "Телефон",
    emoji: "📞",
    color: "#7c3aed",
    isCustom: false,
  },
  {
    id: "charity",
    name: "Благодійність",
    emoji: "❤️",
    color: "#e11d48",
    isCustom: false,
  },
  {
    id: "savings",
    name: "Накопичення",
    emoji: "🏦",
    color: "#059669",
    isCustom: false,
  },
  {
    id: "other",
    name: "Інше",
    emoji: "📦",
    color: "#94a3b8",
    isCustom: false,
  },
];
