import type { Category } from "@/types/expense";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "groceries",
    name: "Продукты",
    emoji: "🛒",
    color: "#22c55e",
    isCustom: false,
  },
  {
    id: "housing",
    name: "Жильё",
    emoji: "🏠",
    color: "#8b5cf6",
    isCustom: false,
  },
  {
    id: "transport",
    name: "Транспорт",
    emoji: "🚗",
    color: "#3b82f6",
    isCustom: false,
  },
  {
    id: "restaurants",
    name: "Рестораны",
    emoji: "🍽️",
    color: "#f97316",
    isCustom: false,
  },
  {
    id: "entertainment",
    name: "Развлечения",
    emoji: "🎬",
    color: "#ec4899",
    isCustom: false,
  },
  {
    id: "health",
    name: "Здоровье",
    emoji: "💊",
    color: "#14b8a6",
    isCustom: false,
  },
  {
    id: "beauty",
    name: "Красота",
    emoji: "💅",
    color: "#f472b6",
    isCustom: false,
  },
  {
    id: "clothes",
    name: "Одежда",
    emoji: "👗",
    color: "#a78bfa",
    isCustom: false,
  },
  {
    id: "education",
    name: "Образование",
    emoji: "📚",
    color: "#06b6d4",
    isCustom: false,
  },
  {
    id: "gifts",
    name: "Подарки",
    emoji: "🎁",
    color: "#f43f5e",
    isCustom: false,
  },
  {
    id: "travel",
    name: "Путешествия",
    emoji: "✈️",
    color: "#0ea5e9",
    isCustom: false,
  },
  {
    id: "subscriptions",
    name: "Подписки",
    emoji: "📱",
    color: "#6366f1",
    isCustom: false,
  },
  {
    id: "pets",
    name: "Питомцы",
    emoji: "🐾",
    color: "#84cc16",
    isCustom: false,
  },
  {
    id: "home",
    name: "Дом и быт",
    emoji: "🧹",
    color: "#eab308",
    isCustom: false,
  },
  {
    id: "tech",
    name: "Техника",
    emoji: "💻",
    color: "#64748b",
    isCustom: false,
  },
  {
    id: "sports",
    name: "Спорт",
    emoji: "🏋️",
    color: "#10b981",
    isCustom: false,
  },
  { id: "taxi", name: "Такси", emoji: "🚕", color: "#fbbf24", isCustom: false },
  {
    id: "coffee",
    name: "Кофе",
    emoji: "☕",
    color: "#92400e",
    isCustom: false,
  },
  {
    id: "utilities",
    name: "ЖКХ",
    emoji: "💡",
    color: "#f59e0b",
    isCustom: false,
  },
  {
    id: "internet",
    name: "Интернет",
    emoji: "🌐",
    color: "#2563eb",
    isCustom: false,
  },
  {
    id: "phone",
    name: "Телефон",
    emoji: "📞",
    color: "#7c3aed",
    isCustom: false,
  },
  {
    id: "charity",
    name: "Благотворительность",
    emoji: "❤️",
    color: "#e11d48",
    isCustom: false,
  },
  {
    id: "savings",
    name: "Накопления",
    emoji: "🏦",
    color: "#059669",
    isCustom: false,
  },
  {
    id: "other",
    name: "Другое",
    emoji: "📦",
    color: "#94a3b8",
    isCustom: false,
  },
];
